[DEFAULT]
# Ignore requirement to use branch name 'master' to make it easier
# for contributors to work with feature and bugfix branches
ignore-branch = True

# Always use pristine tar
pristine-tar = True

# Sign tags
sign-tags = True

# DEP-14 format
debian-branch = debian/bookworm

# Upstream branch continues to be the default 'debian/upstream' and is used for
# upstream tarball imports, with each import tagged 'upstream/%(version)s'.
# Additionally the repository hosts also the actual upstream main branch '4.x'
# and upstream tags so that git-buildpackage can link all of them together.
upstream-vcs-tag=release_%(version)s
